# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    goals: 'package'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target/cx-client-common-9.20.0.jar'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: S3Upload@1
  inputs:
    awsCredentials: 'CxSLDC bucket'
    regionName: 'eu-west-1'
    bucketName: 'cxsdlc'
    sourceFolder: 'target/cx-client-common-9.20.0.jar'
    globExpressions: '**'
    filesAcl: 'bucket-owner-full-control'
